.\" Copyright (C) 2003 Piotr 'Sajmon' Sajmon <sajmon( at )tenboard.com>
.\"
.\" man page for google
.\"
.\" This program is free software; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License
.\" as published by the Free Software Foundation; either version 2
.\" of the License, or (at your option) any later version.
.\"
.TH google 7 "Jul 07, 2003"
.LO 7
.SH NAME:
www.google.pl \- wyszukiwarka internetowa
.SH SK£ADNIA:
.BI www.google.com:
Na stronie g³ównej nale¿y wpisaæ w pole tekstowe s³owo_kluczowe ... (cokolwiek przyjdzie do g³owy)
.SH AUTOR:
Odpowiadaj±cy na setki bzdurnych pytañ, poniewa¿ pytaj±cy kolega nie jest w stanie siê zmusiæ do przeczytania dokumentacji
.SH ZOBACZ TE¯:
man(1)
.SH LICENCJA:
GPL
